springdoc:
  swagger-ui:
    enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?search_path=pet_store
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_schema: pet_store
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
